#!/usr/bin/env bash

# manjaro-polybar-edit: An Manjaro polybar config file editor
# Copyright (C) 2017 Nathaniel <natemaia10@gmail.com>


TITLE="Manjaro Polybar Edit"
ICON="--window-icon=/usr/share/icons/hicolor/scalable/apps/manjaro.svg"
PPATH="$HOME/.config/polybar"
HELP="manjaro-polybar-edit:
\tA script to edit selected polybar configs
\nOptions:
\t-h --help   show this message
\tNo other options are supported.
\nPolybar files must be in $POLYBARPATH
Checkmarked configs will be opened in a text editor"
FILES=($(find "$PPATH" -maxdepth 4 -type f))

case "$@" in
    -h|--help)
        echo -e "$HELP"
        exit 0
esac

edit_Configs() {
    for f in "${FILES[@]}"; do
        if [[ $f = *config ]] || [[ $f = *conf ]] || [[ $f = *.sh ]] || [[ -x $f ]]; then
            NAME=$(sed "s|${HOME}/.config||" <<< "$f")
            LIST="$LIST FALSE $NAME"
        fi
    done
    ANSWER=$(zenity $WINICON --list --title="$TITLE" \
                     --text="<big>Select Polybar Configs or Scripts to edit</big>\n\n" \
                     --checklist --width=450 --height=500 --multiple \
                     --column="Select" --column="File Name" $LIST --separator=" ")
    if [[ $? == 1 ]]; then
        exit 0
    else
        for n in $ANSWER; do
            FULL="$HOME/.config/$n"
            if hash exo-open &>/dev/null; then
                exo-open "$FULL"
            else
                termite -e "$EDITOR $FULL" &>/dev/null &
            fi
        done
    fi
}

edit_Configs

exit 0
