#!/usr/bin/env bash


# Manjaro Graphics Pipemenu
# written by Nathaniel Maia, December 2017

# Add something like this to your menu.xml
# <menu execute="manjaro-graphics-pipemenu" id="graphics" label="Graphics"/>

NAME="graphics"
PNAME="Graphics"
FAIL_MSG="No Apps Installed"

# make sure these two arrays are the same amount of items
# if not things will go wrong and you will have blank space
CMD=(gimp inkscape kdenlive krita openshot pinta gpicview gpick)
DESC=(Gimp Inkscape Kdenlive Krita Openshot Pinta "Picture Viewer" Gpick)

# source lib file
if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
    exit 1
fi

menu_Body() {
    for ((i=0; i<${#CMD[@]}; i++)); do
        if hash "${CMD[$i]}" &>/dev/null; then
            menuItem "${DESC[$i]}" "${CMD[$i]}"
        fi
    done
}

menuStart "$NAME" "$PNAME"
num=0
for x in "${CMD[@]}"; do
    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
done
if [[ $num -gt 0 ]]; then
    menu_Body
else
    menuSeparator "$FAIL_MSG"
fi
menuEnd

exit 0
