#!/usr/bin/env bash

# manjaro-compositor: an Openbox Pipe Menu for use with picom compositor
# Copyright (C) 2012 Philip Newborough <corenominal@corenominal.org>
# Copyright (C) 2013 Aleks-Daniel Jakimenko
# Copyright (C) 2015 John Crawley <john@bunsenlabs.org>

readonly PICOM_CONF="$HOME/.config/picom/picom.conf"
readonly EXECXCOMP="picom -b --config ${PICOM_CONF}"
readonly RESTART_ATTEMPTS=20
readonly HELP="
manjaro-compositor an openbox pipe menu for use with picom
It should normally be called from an openbox menu.

Options (passed from the menu):
    -h --help   show this message
    --start     start the compositor and restart tint2, if running
    --restart   restart the compositor, if running
    --stop      stop the compositor
    --edit      open the picom config file in a text editor
    --watch     restart picom when the config is modified (useful for debugging)

If manjaro-compositor is called with no options (the usual method),
it will output an xml openbox pipemenu for handling compositing.

See ~/.config/picom/picom.conf and 'man picom' for configuration options."

for i in "$@"; do
    case "$i" in
        -h|--help) echo "$HELP" ; exit 0
    esac
done

if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
    echo $"Error: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" >&2 ; exit 1
fi

declareDependencies picom

forcekill_picom() {
    killall -q picom
    for ((i=0; i<RESTART_ATTEMPTS; i++)); do
        [[ $(pidof picom) ]] || break
        killall -q -S KILL picom
        sleep 0.25
    done
}


if [[ $1 = '--edit' ]]; then # Edit picom settings
    if ! [ -e "${PICOM_CONF}" ]; then
        mkdir -p "$HOME/.config/picom"
        cp '/etc/skel/.config/picom/picom.conf' "${PICOM_CONF}"
    fi
    if hash exo-open &>/dev/null; then
        exo-open "${PICOM_CONF}"
    else
        termite -e "$EDITOR ${PICOM_CONF}"
    fi
elif [[ $1 = '--start' ]]; then
    if ! [[ $(pidof picom) ]]; then
        $EXECXCOMP
    else
        echo "$0 --start: Compositor already running" && exit 1
    fi

elif [[ $1 = '--stop' ]]; then
    forcekill_picom

elif [[ $1 = '--restart' ]]; then
    if [[ $(pidof picom) ]]; then
        forcekill_picom
        "$0" --start
    else # nothing to restart
        echo "$0 --restart: Compositor is not running" && exit 1
    fi

elif [[ $1 = '--watch' ]]; then
    while inotifywait -e close_write "${PICOM_CONF}"; do
        "$0" --restart
    done

else
    menuStart
    if ! [[ $(pidof picom) ]]; then
        menuItem 'Enable Compositing' "$0 --start"
    else
        menuItem 'Restart Compositing' "$0 --restart"
        menuItem 'Disable Compositing' "$0 --stop"
        menuSeparator
    fi
    if [[ -e /usr/bin/paranoid.py ]]; then
        menuItem 'Compositor Settings GUI' "paranoid.py"
    fi
    menuItem 'Edit Compositor Config' "$0 --edit"
    menuEnd
fi

exit 0
