#!/usr/bin/env bash


## Declaring some variables
storage="$HOME/.config/openbox/menu-switcher"
menu_cur="$HOME/.config/openbox/menu.xml"
menubase="$HOME/.config/openbox/menu-switcher/menu-static.xml"
backup="$HOME/.config/openbox/menu-switcher/menu-static.xml.bak"

if [[ "$1" == *dynamic ]] || [[ "$1" == *d ]]; then
    if [ -e "$menu_cur" ]; then
        mkdir -p "$storage"
        cp "$menu_cur" "$menubase"
        cp "$menubase" "$backup"
        obmenu-generator -p
    else
        notify-send 'Ooops!' 'Unable to find ~/.config/openbox/menu.xml.. Make sure it exists and try again.'
        exit 1
    fi
elif [[ "$1" == *static ]] || [[ "$1" == *s ]]; then
    if [ -e "$menubase" ]; then
        cp "$menubase" "$menu_cur"
        openbox --reconfigure
    elif [ -e "$backup" ]; then
        cp "$backup" "$menu_cur"
        openbox --reconfigure
    else
        notify-send 'Ooops!' 'Cannot find menu to restore. Please run [switchmenu --dynamic]'
        exit 1
    fi
fi

exit 0
